<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE documento [
    <!ELEMENT documento (p*, imagen?)>
    <!ELEMENT p (#PCDATA|destacar)*> 
    <!ELEMENT destacar (#PCDATA)>
    <!ATTLIST destacar importancia CDATA #IMPLIED>
    <!ELEMENT imagen EMPTY>
    <!ATTLIST imagen fichero CDATA #REQUIRED>
]>
<documento>
    <p>Mi Primer <destacar importancia="alta">documento XML</destacar></p>
    <p>Comienza con la etiqueta &lt;documento&gt;</p>
    <p>A continuaci√≥n colocamos un elemento sin contenido</p>
    <imagen fichero="imagen.gif"/>
</documento>
